name: A-Car
#
on:
  schedule:
    - cron: '0 */1 * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: 'Set up Python'
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
         
      - name: 'Install requirements'
        run: pip install -r ./oooo/C.TXT
        
      - name: '-' 
        run: python3 ./ooo/QCZJ.py
        env:
            Card_telegram: ${{ secrets.Card_telegram }}
            Car_cookies: ${{ secrets.Car_cookies }}
