name: A-DD_buy
#
on:
  schedule:
    - cron: '0 23,4,12,14 * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: 'Set up Python'
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
         
      - name: 'Install requirements'
        run: pip install -r ./ooo/C.TXT
        
      - name: '-' 
        run: python3 ./ooo/DD_buy.py
        env:
            TELE_NOTICE_1: ${{ secrets.TELE_NOTICE_1 }}
            DD_SECRET: ${{ secrets.DD_SECRET }}
            DD_URL: ${{ secrets.DD_URL }}
            DD_COOKIE: ${{ secrets.DD_COOKIE }}
